parameters: {}
environment: {}

packages:
  - name: foo_bot # here
    shared: false
    environment: {
      NODE_ENV: "production"
    }
    parameters: {}
    annotations: {}

    functions:
    - name: handle_webhook # here
      binary: false
      main: ""
      runtime: nodejs:18
      web: true
      webSecure: false
      parameters: {}
      environment: {
        LOG_DESTINATIONS: '[
          {"papertrail":{"token":"${PAPERTRAIL_TOKEN}"}}
        ]',
        OPENAI_API_TOKEN: "${OPENAI_API_TOKEN}",
        TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}",
        STATSD_HOST: "${STATSD_HOST}",
        STATSD_PORT: "${STATSD_PORT}",
        GRAPHITE_API_KEY: "${GRAPHITE_API_KEY}"
      }
      annotations: {}
      limits: {}
