parameters: {}
environment: {}

packages:
  - name: foo_bot # here
    shared: false
    environment: {}
    parameters: {}
    annotations: {}

    functions:
    - name: handle_webhook # here
      binary: false
      main: ""
      runtime: nodejs:18
      web: true
      webSecure: false
      parameters: {}
      environment: {
        LOG_DESTINATIONS: '[
          {"papertrail":{"token":"${PAPERTRAIL_TOKEN}"}}
        ]'
      }
      annotations: {}
      limits: {}
